### ISSUE TITLE
Concerns about the implementation of RECALL

### ISSUE THREAD

**Issue by cchao0116** [hasteck/MRF_NeurIPS_2019#1]
Dear Harald Steck,

It seems the implementation of recall is a little weird (code block [40]) , when I go through the source codes. 

` recall = tmp / np.minimum(k, X_true_binary.sum(axis=1))`)

In conventional, the recall is computed as #hit items / # true items，whereas the recall hereof is equivalent to computing #hit items / min ( #true items, k).

The main concern which I have is about when the k is quite small, the recall in your version would be significantly greater then the latter one, or roughly speaking it behaves more like regular Precision, i.e.,  #hit items / k.

And I also found that the implementation is mirrored from Dawen 's VAE program, do you have any comments to help me better understand this issue? 

Thanks.

**Comment by hasteck** [comment]
Dear Chao Chen,

thanks for bringing up this point. 

This definition makes the recall to be normalized with a maximum value of 1, independent of the test data-set. For instance, if #true_items > k, then the best recall that can be achieved with this definition is k / min(k,#true_items) = 1, while the maximum of the definition #hits / #true_items  is k / #true_items , which is less than 1 and depends on #true_items in the data.

I followed Dawen's VAE code for reproducibility, including this definition of recall. In the end, I think it is only important to be consistent,  i.e., to always use the same definition of the metric when comparing models, and either definition of recall facilitates a useful comparison.

I hope this addresses your concerns.
Thanks,

Harald

**Comment by cchao0116** [comment]
Thank you so much. I agree that it is of critical importance to keep the metrics consistent, although different definitions make it hard to compare empirical results between two different papers.

In the end, I must appreciate your kind help again.
